### ISSUE TITLE
research different technical platforms for the DAO

### ISSUE THREAD

**Issue by sichen1234** [opentaps/open-source-climate-dao#6]
2 options so far:

- DaoStack (daostack.io)
- Telos Decide (https://github.com/telosnetwork/telos-decide)

Are there others out there?

What are the features and benefits of each?

**Comment by Chrisaiki** [comment]
The manual for the telos Decide is here  https://docs.telos.net/developers/telos_contracts/telos-decide
There is an implementation of Telos Decide on Telos tesnet https://app-dev.telos.net/
For technical questions, contact Graig From Mythical Games on the Telos community Telegram group https://t.me/HelloTelos

**Comment by sichen1234** [comment]
Thanks @Chrisaiki  I looked through the Telos Decide docs: Do they offer any particular decisions scheme, such as quorum voting, quadratic voting, or holographic consensus?  Or is it a voting engine that we would program to make decisions based on whatever count of votes we get?

**Comment by sichen1234** [comment]
After some basic research of daostack.io, a summary of what they offer and how it fits with what we're doing:

In daostack, 

- anyone can make a proposal
- there is a group of Predictors who could boost a proposal
- once boosted, the proposal can be passed by a relative majority of those who choose to vote
- if not boosted, the proposal must require an absolute majority to pass

So daostack Predictors are the experts, and they judge if proposals will generally be in line with the group's views.  The Predictors could bring a proposal to a vote faster by boosting, because once boosted the proposal gets approved by a relative majority, whereas unboosted proposals will require an absolute majority, which is slower and harder to get.

The Predictors could be considered "wrong" if:
- A proposal they boost fails
- A proposal they do not boost still wins because enough of the rest of the community votes for it

There is (currently) no quadratic voting.  

Do facts matter?  The ultimate "judge" of whether the proposal was successful or not is going to be an objective, outside measure of CO2 emissions reductions from the proposals chosen by the group.  So the DAO is just there to vote, and the outcome of the DAO's voting will have to be held against an external benchmark.

**Comment by sichen1234** [comment]
Also considering https://aragon.org/ and https://compound.finance/governance

**Comment by sichen1234** [comment]
We have settled on Compound DAO and customized it as part of https://github.com/hyperledger-labs/blockchain-carbon-accounting
